application: safedump-public-key-server
module: default
version: 1
runtime: go
api_version: go1

handlers:
- url: /tasks/.*
  secure: always
  script: _go_app
  login: admin # protects the cron jobs

- url: /
  secure: always
  static_files: index.html
  upload: index.html

- url: /.*
  secure: always
  script: _go_app
