// Code generated by protoc-gen-go.
// source: safedump.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	safedump.proto

It has these top-level messages:
	GetPublicCertRequest
	GetPublicCertResponse
	DecryptSecretRequest
	DecryptSecretResponse
	EncryptedHeader
	ServerConfig
	ClientConfig
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetPublicCertRequest struct {
}

func (m *GetPublicCertRequest) Reset()                    { *m = GetPublicCertRequest{} }
func (m *GetPublicCertRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPublicCertRequest) ProtoMessage()               {}
func (*GetPublicCertRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetPublicCertResponse struct {
	Der []byte `protobuf:"bytes,1,opt,name=der,proto3" json:"der,omitempty"`
}

func (m *GetPublicCertResponse) Reset()                    { *m = GetPublicCertResponse{} }
func (m *GetPublicCertResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPublicCertResponse) ProtoMessage()               {}
func (*GetPublicCertResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetPublicCertResponse) GetDer() []byte {
	if m != nil {
		return m.Der
	}
	return nil
}

type DecryptSecretRequest struct {
	Header *EncryptedHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *DecryptSecretRequest) Reset()                    { *m = DecryptSecretRequest{} }
func (m *DecryptSecretRequest) String() string            { return proto.CompactTextString(m) }
func (*DecryptSecretRequest) ProtoMessage()               {}
func (*DecryptSecretRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DecryptSecretRequest) GetHeader() *EncryptedHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type DecryptSecretResponse struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *DecryptSecretResponse) Reset()                    { *m = DecryptSecretResponse{} }
func (m *DecryptSecretResponse) String() string            { return proto.CompactTextString(m) }
func (*DecryptSecretResponse) ProtoMessage()               {}
func (*DecryptSecretResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DecryptSecretResponse) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type EncryptedHeader struct {
	SpkiFingerprint []byte `protobuf:"bytes,1,opt,name=spki_fingerprint,json=spkiFingerprint,proto3" json:"spki_fingerprint,omitempty"`
	Ttl             int64  `protobuf:"varint,2,opt,name=ttl" json:"ttl,omitempty"`
	EncryptedKey    []byte `protobuf:"bytes,3,opt,name=encrypted_key,json=encryptedKey,proto3" json:"encrypted_key,omitempty"`
}

func (m *EncryptedHeader) Reset()                    { *m = EncryptedHeader{} }
func (m *EncryptedHeader) String() string            { return proto.CompactTextString(m) }
func (*EncryptedHeader) ProtoMessage()               {}
func (*EncryptedHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *EncryptedHeader) GetSpkiFingerprint() []byte {
	if m != nil {
		return m.SpkiFingerprint
	}
	return nil
}

func (m *EncryptedHeader) GetTtl() int64 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *EncryptedHeader) GetEncryptedKey() []byte {
	if m != nil {
		return m.EncryptedKey
	}
	return nil
}

type ServerConfig struct {
	ServerCertPath  string `protobuf:"bytes,1,opt,name=server_cert_path,json=serverCertPath" json:"server_cert_path,omitempty"`
	ServerKeyPath   string `protobuf:"bytes,2,opt,name=server_key_path,json=serverKeyPath" json:"server_key_path,omitempty"`
	ListenBind      string `protobuf:"bytes,3,opt,name=listen_bind,json=listenBind" json:"listen_bind,omitempty"`
	ArchivedKeysDir string `protobuf:"bytes,4,opt,name=archived_keys_dir,json=archivedKeysDir" json:"archived_keys_dir,omitempty"`
	ListenProtocol  string `protobuf:"bytes,5,opt,name=listen_protocol,json=listenProtocol" json:"listen_protocol,omitempty"`
}

func (m *ServerConfig) Reset()                    { *m = ServerConfig{} }
func (m *ServerConfig) String() string            { return proto.CompactTextString(m) }
func (*ServerConfig) ProtoMessage()               {}
func (*ServerConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ServerConfig) GetServerCertPath() string {
	if m != nil {
		return m.ServerCertPath
	}
	return ""
}

func (m *ServerConfig) GetServerKeyPath() string {
	if m != nil {
		return m.ServerKeyPath
	}
	return ""
}

func (m *ServerConfig) GetListenBind() string {
	if m != nil {
		return m.ListenBind
	}
	return ""
}

func (m *ServerConfig) GetArchivedKeysDir() string {
	if m != nil {
		return m.ArchivedKeysDir
	}
	return ""
}

func (m *ServerConfig) GetListenProtocol() string {
	if m != nil {
		return m.ListenProtocol
	}
	return ""
}

type ClientConfig struct {
	NoGrpcSecurity     bool   `protobuf:"varint,1,opt,name=no_grpc_security,json=noGrpcSecurity" json:"no_grpc_security,omitempty"`
	UseSystemCaForGrpc bool   `protobuf:"varint,2,opt,name=use_system_ca_for_grpc,json=useSystemCaForGrpc" json:"use_system_ca_for_grpc,omitempty"`
	GrpcCert           string `protobuf:"bytes,3,opt,name=grpc_cert,json=grpcCert" json:"grpc_cert,omitempty"`
	GrpcServer         string `protobuf:"bytes,4,opt,name=grpc_server,json=grpcServer" json:"grpc_server,omitempty"`
}

func (m *ClientConfig) Reset()                    { *m = ClientConfig{} }
func (m *ClientConfig) String() string            { return proto.CompactTextString(m) }
func (*ClientConfig) ProtoMessage()               {}
func (*ClientConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ClientConfig) GetNoGrpcSecurity() bool {
	if m != nil {
		return m.NoGrpcSecurity
	}
	return false
}

func (m *ClientConfig) GetUseSystemCaForGrpc() bool {
	if m != nil {
		return m.UseSystemCaForGrpc
	}
	return false
}

func (m *ClientConfig) GetGrpcCert() string {
	if m != nil {
		return m.GrpcCert
	}
	return ""
}

func (m *ClientConfig) GetGrpcServer() string {
	if m != nil {
		return m.GrpcServer
	}
	return ""
}

func init() {
	proto.RegisterType((*GetPublicCertRequest)(nil), "continusec.safedump.GetPublicCertRequest")
	proto.RegisterType((*GetPublicCertResponse)(nil), "continusec.safedump.GetPublicCertResponse")
	proto.RegisterType((*DecryptSecretRequest)(nil), "continusec.safedump.DecryptSecretRequest")
	proto.RegisterType((*DecryptSecretResponse)(nil), "continusec.safedump.DecryptSecretResponse")
	proto.RegisterType((*EncryptedHeader)(nil), "continusec.safedump.EncryptedHeader")
	proto.RegisterType((*ServerConfig)(nil), "continusec.safedump.ServerConfig")
	proto.RegisterType((*ClientConfig)(nil), "continusec.safedump.ClientConfig")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SafeDumpService service

type SafeDumpServiceClient interface {
	GetPublicCert(ctx context.Context, in *GetPublicCertRequest, opts ...grpc.CallOption) (*GetPublicCertResponse, error)
	DecryptSecret(ctx context.Context, in *DecryptSecretRequest, opts ...grpc.CallOption) (*DecryptSecretResponse, error)
}

type safeDumpServiceClient struct {
	cc *grpc.ClientConn
}

func NewSafeDumpServiceClient(cc *grpc.ClientConn) SafeDumpServiceClient {
	return &safeDumpServiceClient{cc}
}

func (c *safeDumpServiceClient) GetPublicCert(ctx context.Context, in *GetPublicCertRequest, opts ...grpc.CallOption) (*GetPublicCertResponse, error) {
	out := new(GetPublicCertResponse)
	err := grpc.Invoke(ctx, "/continusec.safedump.SafeDumpService/GetPublicCert", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *safeDumpServiceClient) DecryptSecret(ctx context.Context, in *DecryptSecretRequest, opts ...grpc.CallOption) (*DecryptSecretResponse, error) {
	out := new(DecryptSecretResponse)
	err := grpc.Invoke(ctx, "/continusec.safedump.SafeDumpService/DecryptSecret", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SafeDumpService service

type SafeDumpServiceServer interface {
	GetPublicCert(context.Context, *GetPublicCertRequest) (*GetPublicCertResponse, error)
	DecryptSecret(context.Context, *DecryptSecretRequest) (*DecryptSecretResponse, error)
}

func RegisterSafeDumpServiceServer(s *grpc.Server, srv SafeDumpServiceServer) {
	s.RegisterService(&_SafeDumpService_serviceDesc, srv)
}

func _SafeDumpService_GetPublicCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafeDumpServiceServer).GetPublicCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/continusec.safedump.SafeDumpService/GetPublicCert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafeDumpServiceServer).GetPublicCert(ctx, req.(*GetPublicCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SafeDumpService_DecryptSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafeDumpServiceServer).DecryptSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/continusec.safedump.SafeDumpService/DecryptSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafeDumpServiceServer).DecryptSecret(ctx, req.(*DecryptSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SafeDumpService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "continusec.safedump.SafeDumpService",
	HandlerType: (*SafeDumpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublicCert",
			Handler:    _SafeDumpService_GetPublicCert_Handler,
		},
		{
			MethodName: "DecryptSecret",
			Handler:    _SafeDumpService_DecryptSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "safedump.proto",
}

func init() { proto.RegisterFile("safedump.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 507 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0xc1, 0x6e, 0x1a, 0x31,
	0x14, 0xcc, 0x42, 0x1a, 0xc1, 0x0b, 0xb0, 0xd4, 0x4d, 0x23, 0xd4, 0x1e, 0x1a, 0x6d, 0xab, 0x16,
	0x72, 0xe0, 0x40, 0xaf, 0x3d, 0x05, 0x9a, 0x54, 0xe2, 0x82, 0x96, 0x9e, 0x7a, 0xb1, 0x16, 0xef,
	0x03, 0x2c, 0xc0, 0x76, 0x6d, 0x6f, 0xa4, 0xfd, 0xa5, 0x7e, 0x50, 0xff, 0xa0, 0xff, 0x51, 0xd9,
	0xbb, 0x5b, 0x14, 0xb4, 0x91, 0x7a, 0x33, 0xe3, 0x79, 0x33, 0xe3, 0xc7, 0x2c, 0xf4, 0x4c, 0xb2,
	0xc6, 0x34, 0x3b, 0xa8, 0xb1, 0xd2, 0xd2, 0x4a, 0xf2, 0x8a, 0x49, 0x61, 0xb9, 0xc8, 0x0c, 0xb2,
	0x71, 0x75, 0x15, 0x5d, 0xc3, 0xd5, 0x03, 0xda, 0x45, 0xb6, 0xda, 0x73, 0x36, 0x45, 0x6d, 0x63,
	0xfc, 0x99, 0xa1, 0xb1, 0xd1, 0x08, 0x5e, 0x9f, 0xe0, 0x46, 0x49, 0x61, 0x90, 0xf4, 0xa1, 0x99,
	0xa2, 0x1e, 0x04, 0x37, 0xc1, 0xb0, 0x13, 0xbb, 0x63, 0xf4, 0x1d, 0xae, 0x66, 0xc8, 0x74, 0xae,
	0xec, 0x12, 0x99, 0xc6, 0x4a, 0x82, 0x7c, 0x81, 0x8b, 0x2d, 0x26, 0x15, 0xf9, 0x72, 0xf2, 0x61,
	0x5c, 0x13, 0x60, 0xfc, 0x55, 0xf8, 0x51, 0x4c, 0xbf, 0x79, 0x6e, 0x5c, 0xce, 0xb8, 0x00, 0x27,
	0xaa, 0xc7, 0x00, 0x3b, 0xcc, 0xab, 0x00, 0x3b, 0xcc, 0x23, 0x03, 0xe1, 0x89, 0x0a, 0x19, 0x41,
	0xdf, 0xa8, 0x1d, 0xa7, 0x6b, 0x2e, 0x36, 0xa8, 0x95, 0xe6, 0xc2, 0x96, 0x13, 0xa1, 0xc3, 0xef,
	0x8f, 0xb0, 0xd3, 0xb3, 0x76, 0x3f, 0x68, 0xdc, 0x04, 0xc3, 0x66, 0xec, 0x8e, 0xe4, 0x3d, 0x74,
	0xb1, 0xd2, 0xa3, 0xce, 0xab, 0xe9, 0x27, 0x3b, 0xff, 0xc0, 0x39, 0xe6, 0xd1, 0xef, 0x00, 0x3a,
	0x4b, 0xd4, 0x8f, 0xa8, 0xa7, 0x52, 0xac, 0xf9, 0x86, 0x0c, 0xa1, 0x6f, 0xfc, 0x6f, 0xca, 0x50,
	0x5b, 0xaa, 0x12, 0xbb, 0xf5, 0x96, 0xed, 0xb8, 0x57, 0xe0, 0x6e, 0x8d, 0x8b, 0xc4, 0x6e, 0xc9,
	0x47, 0x08, 0x4b, 0xe6, 0x0e, 0xf3, 0x82, 0xd8, 0xf0, 0xc4, 0x6e, 0x01, 0xcf, 0x31, 0xf7, 0xbc,
	0x77, 0x70, 0xb9, 0xe7, 0xc6, 0xa2, 0xa0, 0x2b, 0x2e, 0x52, 0x9f, 0xa2, 0x1d, 0x43, 0x01, 0xdd,
	0x71, 0x91, 0x92, 0x5b, 0x78, 0x99, 0x68, 0xb6, 0xe5, 0x8f, 0x45, 0x4e, 0x43, 0x53, 0xae, 0x07,
	0xe7, 0x9e, 0x16, 0x56, 0x17, 0x73, 0xcc, 0xcd, 0x8c, 0x6b, 0xf2, 0x09, 0xc2, 0x52, 0xcc, 0xb7,
	0x81, 0xc9, 0xfd, 0xe0, 0x45, 0x91, 0xae, 0x80, 0x17, 0x25, 0x1a, 0xfd, 0x0a, 0xa0, 0x33, 0xdd,
	0x73, 0x14, 0xf6, 0xf8, 0x30, 0x21, 0xe9, 0x46, 0x2b, 0x46, 0x0d, 0xb2, 0x4c, 0x73, 0x5b, 0x6c,
	0xbf, 0x15, 0xf7, 0x84, 0x7c, 0xd0, 0x8a, 0x2d, 0x4b, 0x94, 0x4c, 0xe0, 0x3a, 0x33, 0x48, 0x4d,
	0x6e, 0x2c, 0x1e, 0x28, 0x4b, 0xe8, 0x5a, 0x6a, 0x3f, 0xe8, 0xdf, 0xd7, 0x8a, 0x49, 0x66, 0x70,
	0xe9, 0x2f, 0xa7, 0xc9, 0xbd, 0xd4, 0x6e, 0x96, 0xbc, 0x85, 0xb6, 0x97, 0x76, 0x4b, 0x2b, 0x9f,
	0xd8, 0x72, 0x80, 0xdb, 0x96, 0xdb, 0x40, 0xe9, 0xeb, 0xf6, 0x52, 0x3e, 0x0d, 0x36, 0xde, 0xd3,
	0x21, 0x93, 0x3f, 0x01, 0x84, 0xcb, 0x64, 0x8d, 0xb3, 0xec, 0xa0, 0x1c, 0xc4, 0x19, 0x92, 0x2d,
	0x74, 0x9f, 0x54, 0x97, 0x8c, 0x6a, 0x8b, 0x57, 0x57, 0xfb, 0x37, 0xb7, 0xff, 0x43, 0x2d, 0x8a,
	0x18, 0x9d, 0x39, 0xa7, 0x27, 0x1d, 0x7d, 0xc6, 0xa9, 0xee, 0xeb, 0x78, 0xc6, 0xa9, 0xb6, 0xf2,
	0xd1, 0xd9, 0xdd, 0xf9, 0x8f, 0x86, 0x5a, 0xad, 0x2e, 0xfc, 0x5f, 0xf7, 0xf9, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xae, 0x24, 0x9d, 0xdb, 0xda, 0x03, 0x00, 0x00,
}
