// Code generated by protoc-gen-go.
// source: safedump.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	safedump.proto

It has these top-level messages:
	GetPublicCertRequest
	GetPublicCertResponse
	DecryptSecretRequest
	DecryptSecretResponse
	EncryptedHeader
	ServerConfig
	ClientConfig
	KeyAndCert
	PersistedObject
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServerProtocol int32

const (
	ServerProtocol_GRPC_PROTOCOL ServerProtocol = 0
	ServerProtocol_HTTP_PROTOCOL ServerProtocol = 1
)

var ServerProtocol_name = map[int32]string{
	0: "GRPC_PROTOCOL",
	1: "HTTP_PROTOCOL",
}
var ServerProtocol_value = map[string]int32{
	"GRPC_PROTOCOL": 0,
	"HTTP_PROTOCOL": 1,
}

func (x ServerProtocol) String() string {
	return proto.EnumName(ServerProtocol_name, int32(x))
}
func (ServerProtocol) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetPublicCertRequest struct {
}

func (m *GetPublicCertRequest) Reset()                    { *m = GetPublicCertRequest{} }
func (m *GetPublicCertRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPublicCertRequest) ProtoMessage()               {}
func (*GetPublicCertRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetPublicCertResponse struct {
	Der []byte `protobuf:"bytes,1,opt,name=der,proto3" json:"der,omitempty"`
	Ttl int64  `protobuf:"varint,2,opt,name=ttl" json:"ttl,omitempty"`
}

func (m *GetPublicCertResponse) Reset()                    { *m = GetPublicCertResponse{} }
func (m *GetPublicCertResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPublicCertResponse) ProtoMessage()               {}
func (*GetPublicCertResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetPublicCertResponse) GetDer() []byte {
	if m != nil {
		return m.Der
	}
	return nil
}

func (m *GetPublicCertResponse) GetTtl() int64 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type DecryptSecretRequest struct {
	Header *EncryptedHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *DecryptSecretRequest) Reset()                    { *m = DecryptSecretRequest{} }
func (m *DecryptSecretRequest) String() string            { return proto.CompactTextString(m) }
func (*DecryptSecretRequest) ProtoMessage()               {}
func (*DecryptSecretRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DecryptSecretRequest) GetHeader() *EncryptedHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type DecryptSecretResponse struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *DecryptSecretResponse) Reset()                    { *m = DecryptSecretResponse{} }
func (m *DecryptSecretResponse) String() string            { return proto.CompactTextString(m) }
func (*DecryptSecretResponse) ProtoMessage()               {}
func (*DecryptSecretResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DecryptSecretResponse) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type EncryptedHeader struct {
	SpkiFingerprint []byte `protobuf:"bytes,1,opt,name=spki_fingerprint,json=spkiFingerprint,proto3" json:"spki_fingerprint,omitempty"`
	Ttl             int64  `protobuf:"varint,2,opt,name=ttl" json:"ttl,omitempty"`
	EncryptedKey    []byte `protobuf:"bytes,3,opt,name=encrypted_key,json=encryptedKey,proto3" json:"encrypted_key,omitempty"`
}

func (m *EncryptedHeader) Reset()                    { *m = EncryptedHeader{} }
func (m *EncryptedHeader) String() string            { return proto.CompactTextString(m) }
func (*EncryptedHeader) ProtoMessage()               {}
func (*EncryptedHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *EncryptedHeader) GetSpkiFingerprint() []byte {
	if m != nil {
		return m.SpkiFingerprint
	}
	return nil
}

func (m *EncryptedHeader) GetTtl() int64 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *EncryptedHeader) GetEncryptedKey() []byte {
	if m != nil {
		return m.EncryptedKey
	}
	return nil
}

type ServerConfig struct {
	ServerCertPath            string `protobuf:"bytes,1,opt,name=server_cert_path,json=serverCertPath" json:"server_cert_path,omitempty"`
	ServerKeyPath             string `protobuf:"bytes,2,opt,name=server_key_path,json=serverKeyPath" json:"server_key_path,omitempty"`
	ListenBind                string `protobuf:"bytes,3,opt,name=listen_bind,json=listenBind" json:"listen_bind,omitempty"`
	ArchivedKeysDir           string `protobuf:"bytes,4,opt,name=archived_keys_dir,json=archivedKeysDir" json:"archived_keys_dir,omitempty"`
	ListenProtocol            string `protobuf:"bytes,5,opt,name=listen_protocol,json=listenProtocol" json:"listen_protocol,omitempty"`
	MaxDecryptionPeriod       string `protobuf:"bytes,6,opt,name=max_decryption_period,json=maxDecryptionPeriod" json:"max_decryption_period,omitempty"`
	CertificateRotationPeriod string `protobuf:"bytes,7,opt,name=certificate_rotation_period,json=certificateRotationPeriod" json:"certificate_rotation_period,omitempty"`
	PurgeOldKeys              bool   `protobuf:"varint,8,opt,name=purge_old_keys,json=purgeOldKeys" json:"purge_old_keys,omitempty"`
	KeyRetentionPeriod        string `protobuf:"bytes,9,opt,name=key_retention_period,json=keyRetentionPeriod" json:"key_retention_period,omitempty"`
}

func (m *ServerConfig) Reset()                    { *m = ServerConfig{} }
func (m *ServerConfig) String() string            { return proto.CompactTextString(m) }
func (*ServerConfig) ProtoMessage()               {}
func (*ServerConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ServerConfig) GetServerCertPath() string {
	if m != nil {
		return m.ServerCertPath
	}
	return ""
}

func (m *ServerConfig) GetServerKeyPath() string {
	if m != nil {
		return m.ServerKeyPath
	}
	return ""
}

func (m *ServerConfig) GetListenBind() string {
	if m != nil {
		return m.ListenBind
	}
	return ""
}

func (m *ServerConfig) GetArchivedKeysDir() string {
	if m != nil {
		return m.ArchivedKeysDir
	}
	return ""
}

func (m *ServerConfig) GetListenProtocol() string {
	if m != nil {
		return m.ListenProtocol
	}
	return ""
}

func (m *ServerConfig) GetMaxDecryptionPeriod() string {
	if m != nil {
		return m.MaxDecryptionPeriod
	}
	return ""
}

func (m *ServerConfig) GetCertificateRotationPeriod() string {
	if m != nil {
		return m.CertificateRotationPeriod
	}
	return ""
}

func (m *ServerConfig) GetPurgeOldKeys() bool {
	if m != nil {
		return m.PurgeOldKeys
	}
	return false
}

func (m *ServerConfig) GetKeyRetentionPeriod() string {
	if m != nil {
		return m.KeyRetentionPeriod
	}
	return ""
}

type ClientConfig struct {
	NoGrpcSecurity     bool           `protobuf:"varint,1,opt,name=no_grpc_security,json=noGrpcSecurity" json:"no_grpc_security,omitempty"`
	UseSystemCaForGrpc bool           `protobuf:"varint,2,opt,name=use_system_ca_for_grpc,json=useSystemCaForGrpc" json:"use_system_ca_for_grpc,omitempty"`
	GrpcCert           string         `protobuf:"bytes,3,opt,name=grpc_cert,json=grpcCert" json:"grpc_cert,omitempty"`
	GrpcServer         string         `protobuf:"bytes,4,opt,name=grpc_server,json=grpcServer" json:"grpc_server,omitempty"`
	HttpBaseUrl        string         `protobuf:"bytes,5,opt,name=http_base_url,json=httpBaseUrl" json:"http_base_url,omitempty"`
	Protocol           ServerProtocol `protobuf:"varint,6,opt,name=protocol,enum=continusec.safedump.ServerProtocol" json:"protocol,omitempty"`
}

func (m *ClientConfig) Reset()                    { *m = ClientConfig{} }
func (m *ClientConfig) String() string            { return proto.CompactTextString(m) }
func (*ClientConfig) ProtoMessage()               {}
func (*ClientConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ClientConfig) GetNoGrpcSecurity() bool {
	if m != nil {
		return m.NoGrpcSecurity
	}
	return false
}

func (m *ClientConfig) GetUseSystemCaForGrpc() bool {
	if m != nil {
		return m.UseSystemCaForGrpc
	}
	return false
}

func (m *ClientConfig) GetGrpcCert() string {
	if m != nil {
		return m.GrpcCert
	}
	return ""
}

func (m *ClientConfig) GetGrpcServer() string {
	if m != nil {
		return m.GrpcServer
	}
	return ""
}

func (m *ClientConfig) GetHttpBaseUrl() string {
	if m != nil {
		return m.HttpBaseUrl
	}
	return ""
}

func (m *ClientConfig) GetProtocol() ServerProtocol {
	if m != nil {
		return m.Protocol
	}
	return ServerProtocol_GRPC_PROTOCOL
}

type KeyAndCert struct {
	Cert *GetPublicCertResponse `protobuf:"bytes,1,opt,name=cert" json:"cert,omitempty"`
	Key  []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *KeyAndCert) Reset()                    { *m = KeyAndCert{} }
func (m *KeyAndCert) String() string            { return proto.CompactTextString(m) }
func (*KeyAndCert) ProtoMessage()               {}
func (*KeyAndCert) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *KeyAndCert) GetCert() *GetPublicCertResponse {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *KeyAndCert) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type PersistedObject struct {
	Ttl   int64  `protobuf:"varint,1,opt,name=ttl" json:"ttl,omitempty"`
	Key   []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *PersistedObject) Reset()                    { *m = PersistedObject{} }
func (m *PersistedObject) String() string            { return proto.CompactTextString(m) }
func (*PersistedObject) ProtoMessage()               {}
func (*PersistedObject) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PersistedObject) GetTtl() int64 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *PersistedObject) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PersistedObject) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*GetPublicCertRequest)(nil), "continusec.safedump.GetPublicCertRequest")
	proto.RegisterType((*GetPublicCertResponse)(nil), "continusec.safedump.GetPublicCertResponse")
	proto.RegisterType((*DecryptSecretRequest)(nil), "continusec.safedump.DecryptSecretRequest")
	proto.RegisterType((*DecryptSecretResponse)(nil), "continusec.safedump.DecryptSecretResponse")
	proto.RegisterType((*EncryptedHeader)(nil), "continusec.safedump.EncryptedHeader")
	proto.RegisterType((*ServerConfig)(nil), "continusec.safedump.ServerConfig")
	proto.RegisterType((*ClientConfig)(nil), "continusec.safedump.ClientConfig")
	proto.RegisterType((*KeyAndCert)(nil), "continusec.safedump.KeyAndCert")
	proto.RegisterType((*PersistedObject)(nil), "continusec.safedump.PersistedObject")
	proto.RegisterEnum("continusec.safedump.ServerProtocol", ServerProtocol_name, ServerProtocol_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SafeDumpService service

type SafeDumpServiceClient interface {
	GetPublicCert(ctx context.Context, in *GetPublicCertRequest, opts ...grpc.CallOption) (*GetPublicCertResponse, error)
	DecryptSecret(ctx context.Context, in *DecryptSecretRequest, opts ...grpc.CallOption) (*DecryptSecretResponse, error)
}

type safeDumpServiceClient struct {
	cc *grpc.ClientConn
}

func NewSafeDumpServiceClient(cc *grpc.ClientConn) SafeDumpServiceClient {
	return &safeDumpServiceClient{cc}
}

func (c *safeDumpServiceClient) GetPublicCert(ctx context.Context, in *GetPublicCertRequest, opts ...grpc.CallOption) (*GetPublicCertResponse, error) {
	out := new(GetPublicCertResponse)
	err := grpc.Invoke(ctx, "/continusec.safedump.SafeDumpService/GetPublicCert", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *safeDumpServiceClient) DecryptSecret(ctx context.Context, in *DecryptSecretRequest, opts ...grpc.CallOption) (*DecryptSecretResponse, error) {
	out := new(DecryptSecretResponse)
	err := grpc.Invoke(ctx, "/continusec.safedump.SafeDumpService/DecryptSecret", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SafeDumpService service

type SafeDumpServiceServer interface {
	GetPublicCert(context.Context, *GetPublicCertRequest) (*GetPublicCertResponse, error)
	DecryptSecret(context.Context, *DecryptSecretRequest) (*DecryptSecretResponse, error)
}

func RegisterSafeDumpServiceServer(s *grpc.Server, srv SafeDumpServiceServer) {
	s.RegisterService(&_SafeDumpService_serviceDesc, srv)
}

func _SafeDumpService_GetPublicCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafeDumpServiceServer).GetPublicCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/continusec.safedump.SafeDumpService/GetPublicCert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafeDumpServiceServer).GetPublicCert(ctx, req.(*GetPublicCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SafeDumpService_DecryptSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafeDumpServiceServer).DecryptSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/continusec.safedump.SafeDumpService/DecryptSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafeDumpServiceServer).DecryptSecret(ctx, req.(*DecryptSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SafeDumpService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "continusec.safedump.SafeDumpService",
	HandlerType: (*SafeDumpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublicCert",
			Handler:    _SafeDumpService_GetPublicCert_Handler,
		},
		{
			MethodName: "DecryptSecret",
			Handler:    _SafeDumpService_DecryptSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "safedump.proto",
}

func init() { proto.RegisterFile("safedump.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 747 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x6e, 0xe2, 0x46,
	0x14, 0x0e, 0x90, 0xa4, 0x70, 0xc2, 0x5f, 0x26, 0x24, 0xa2, 0xcd, 0x45, 0x23, 0x27, 0x6a, 0x49,
	0x2e, 0x50, 0x45, 0xa5, 0xde, 0xb4, 0x4a, 0xd5, 0x40, 0x93, 0x48, 0x54, 0xc2, 0x32, 0xf4, 0x66,
	0x2f, 0x76, 0x64, 0xec, 0x03, 0xcc, 0x62, 0xc6, 0xde, 0x99, 0x71, 0x14, 0x3f, 0xc5, 0xbe, 0xc3,
	0xbe, 0xdb, 0xbe, 0xc7, 0x6a, 0xc6, 0x36, 0xe4, 0x87, 0x48, 0xbb, 0x77, 0xf6, 0x77, 0xce, 0xf7,
	0x9d, 0x73, 0xe6, 0x9b, 0x33, 0x50, 0x97, 0xee, 0x0c, 0xfd, 0x78, 0x15, 0x75, 0x23, 0x11, 0xaa,
	0x90, 0x1c, 0x79, 0x21, 0x57, 0x8c, 0xc7, 0x12, 0xbd, 0x6e, 0x1e, 0xb2, 0x4e, 0xa0, 0x75, 0x87,
	0xca, 0x8e, 0xa7, 0x01, 0xf3, 0xfa, 0x28, 0x94, 0x83, 0x1f, 0x63, 0x94, 0xca, 0xfa, 0x13, 0x8e,
	0x5f, 0xe0, 0x32, 0x0a, 0xb9, 0x44, 0xd2, 0x84, 0x92, 0x8f, 0xa2, 0x5d, 0x38, 0x2b, 0x74, 0xaa,
	0x8e, 0xfe, 0xd4, 0x88, 0x52, 0x41, 0xbb, 0x78, 0x56, 0xe8, 0x94, 0x1c, 0xfd, 0x69, 0x4d, 0xa0,
	0x35, 0x40, 0x4f, 0x24, 0x91, 0x1a, 0xa3, 0x27, 0x30, 0x17, 0x25, 0x7f, 0xc1, 0xfe, 0x02, 0xdd,
	0x9c, 0x7e, 0xd0, 0xbb, 0xe8, 0x6e, 0x69, 0xa9, 0xfb, 0x2f, 0x37, 0x54, 0xf4, 0xef, 0x4d, 0xae,
	0x93, 0x71, 0xac, 0x4b, 0x38, 0x7e, 0xa1, 0xba, 0x69, 0x69, 0x89, 0x49, 0xde, 0xd2, 0x12, 0x13,
	0x4b, 0x42, 0xe3, 0x85, 0x0a, 0xb9, 0x84, 0xa6, 0x8c, 0x96, 0x8c, 0xce, 0x18, 0x9f, 0xa3, 0x88,
	0x04, 0xe3, 0x2a, 0x63, 0x34, 0x34, 0x7e, 0xbb, 0x81, 0x5f, 0x0f, 0x44, 0xce, 0xa1, 0x86, 0xb9,
	0x1e, 0xd5, 0xb5, 0x4a, 0x86, 0x59, 0x5d, 0x83, 0x43, 0x4c, 0xac, 0xcf, 0x25, 0xa8, 0x8e, 0x51,
	0x3c, 0xa0, 0xe8, 0x87, 0x7c, 0xc6, 0xe6, 0xa4, 0x03, 0x4d, 0x69, 0xfe, 0xa9, 0x87, 0x42, 0xd1,
	0xc8, 0x55, 0x0b, 0x53, 0xb2, 0xe2, 0xd4, 0x53, 0x5c, 0x1f, 0xac, 0xed, 0xaa, 0x05, 0xf9, 0x05,
	0x1a, 0x59, 0xe6, 0x12, 0x93, 0x34, 0xb1, 0x68, 0x12, 0x6b, 0x29, 0x3c, 0xc4, 0xc4, 0xe4, 0xfd,
	0x0c, 0x07, 0x01, 0x93, 0x0a, 0x39, 0x9d, 0x32, 0xee, 0x9b, 0x2e, 0x2a, 0x0e, 0xa4, 0xd0, 0x0d,
	0xe3, 0x3e, 0xb9, 0x82, 0x43, 0x57, 0x78, 0x0b, 0xf6, 0x90, 0xf6, 0x29, 0xa9, 0xcf, 0x44, 0x7b,
	0xd7, 0xa4, 0x35, 0xf2, 0xc0, 0x10, 0x13, 0x39, 0x60, 0x82, 0xfc, 0x0a, 0x8d, 0x4c, 0xcc, 0xdc,
	0x0f, 0x2f, 0x0c, 0xda, 0x7b, 0x69, 0x77, 0x29, 0x6c, 0x67, 0x28, 0xe9, 0xc1, 0xf1, 0xca, 0x7d,
	0xa4, 0x7e, 0x7a, 0xf8, 0x2c, 0xe4, 0x34, 0x42, 0xc1, 0x42, 0xbf, 0xbd, 0x6f, 0xd2, 0x8f, 0x56,
	0xee, 0xe3, 0x60, 0x1d, 0xb3, 0x4d, 0x88, 0x5c, 0xc3, 0xa9, 0x1e, 0x9a, 0xcd, 0x98, 0xe7, 0x2a,
	0xa4, 0x22, 0x54, 0xee, 0x53, 0xe6, 0x0f, 0x86, 0xf9, 0xe3, 0x93, 0x14, 0x27, 0xcb, 0xc8, 0xf8,
	0x17, 0x50, 0x8f, 0x62, 0x31, 0x47, 0x1a, 0x06, 0xe9, 0x24, 0xed, 0xf2, 0x59, 0xa1, 0x53, 0x76,
	0xaa, 0x06, 0x1d, 0x05, 0x66, 0x0a, 0xf2, 0x1b, 0xb4, 0xf4, 0x81, 0x09, 0x54, 0xc8, 0x9f, 0xca,
	0x57, 0x8c, 0x3c, 0x59, 0x62, 0xe2, 0xe4, 0xa1, 0x54, 0xd7, 0xfa, 0x54, 0x84, 0x6a, 0x3f, 0x60,
	0xc8, 0xd5, 0xc6, 0x24, 0x1e, 0xd2, 0xb9, 0x88, 0x3c, 0x2a, 0xd1, 0x8b, 0x05, 0x53, 0xe9, 0x4d,
	0x2a, 0x3b, 0x75, 0x1e, 0xde, 0x89, 0xc8, 0x1b, 0x67, 0x28, 0xe9, 0xc1, 0x49, 0x2c, 0x91, 0xca,
	0x44, 0x2a, 0x5c, 0x51, 0xcf, 0xa5, 0xb3, 0x50, 0x18, 0xa2, 0xf1, 0xaa, 0xec, 0x90, 0x58, 0xe2,
	0xd8, 0x04, 0xfb, 0xee, 0x6d, 0x28, 0x34, 0x97, 0x9c, 0x42, 0xc5, 0x48, 0xeb, 0x41, 0x33, 0xbb,
	0xca, 0x1a, 0xd0, 0xce, 0x6b, 0x37, 0xb3, 0xba, 0xda, 0xe3, 0xcc, 0x26, 0x98, 0x9b, 0x9a, 0x1a,
	0x21, 0x16, 0xd4, 0x16, 0x4a, 0x45, 0x74, 0xea, 0x4a, 0xa4, 0xb1, 0xc8, 0xfd, 0x39, 0xd0, 0xe0,
	0x8d, 0x2b, 0xf1, 0x7f, 0x11, 0x90, 0xbf, 0xa1, 0xbc, 0xb6, 0x4f, 0xfb, 0x51, 0xef, 0x9d, 0x6f,
	0xdd, 0xaa, 0x54, 0x32, 0xf7, 0xd4, 0x59, 0x93, 0xac, 0xf7, 0x00, 0x43, 0x4c, 0xfe, 0xe1, 0xbe,
	0xe9, 0xe9, 0x1a, 0x76, 0x4d, 0xaf, 0xe9, 0x82, 0x5e, 0x6d, 0x95, 0xda, 0xfa, 0x30, 0x38, 0x86,
	0x97, 0xef, 0x62, 0x71, 0xb3, 0x8b, 0x43, 0x68, 0xd8, 0x28, 0xa4, 0xbe, 0x52, 0xfe, 0x68, 0xfa,
	0x01, 0xbd, 0xf5, 0x82, 0x15, 0x36, 0x0b, 0xf6, 0x8a, 0x46, 0x5a, 0xb0, 0xf7, 0xe0, 0x06, 0x31,
	0x66, 0xab, 0x96, 0xfe, 0x5c, 0xfd, 0x01, 0xf5, 0xe7, 0x83, 0x90, 0x43, 0xa8, 0xdd, 0x39, 0x76,
	0x9f, 0xda, 0xce, 0x68, 0x32, 0xea, 0x8f, 0xfe, 0x6b, 0xee, 0x68, 0xe8, 0x7e, 0x32, 0xb1, 0x37,
	0x50, 0xa1, 0xf7, 0xa5, 0x00, 0x8d, 0xb1, 0x3b, 0xc3, 0x41, 0xbc, 0x8a, 0xb4, 0x00, 0xf3, 0x90,
	0x2c, 0xa0, 0xf6, 0x6c, 0x12, 0x72, 0xf9, 0x2d, 0xd3, 0x9a, 0x97, 0xec, 0xa7, 0xef, 0x38, 0x18,
	0x6b, 0x47, 0x57, 0x7a, 0xf6, 0x72, 0xbd, 0x51, 0x69, 0xdb, 0x9b, 0xf9, 0x46, 0xa5, 0xad, 0x0f,
	0xa1, 0xb5, 0x73, 0xb3, 0xfb, 0xae, 0x18, 0x4d, 0xa7, 0xfb, 0xc6, 0xdc, 0xdf, 0xbf, 0x06, 0x00,
	0x00, 0xff, 0xff, 0xdf, 0x6a, 0xbf, 0xcb, 0x02, 0x06, 0x00, 0x00,
}
